**SUPPORT VECTOR MACHINE (SVM) **

In [65]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

In [66]:
df = pd.read_csv("Iris.csv")

In [67]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [68]:
df = df.drop(columns='Id')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [70]:
X = df.drop(columns='Species')
y = df['Species']

In [71]:
# svm = SVC(kernel='linear',C=0.001,gamma=0.1). This has accuracy score = 0.96
svm = SVC(kernel='linear',C=0.1,gamma=0.1) #This has accuracy score of = 1.00
svm.fit(X, y)

SVC(C=0.1, gamma=0.1, kernel='linear')

In [72]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [73]:
y_pred = svm.predict(X_test)

In [74]:
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [75]:
acc_score = accuracy_score(y_test,y_pred)

In [76]:
acc_score

1.0

In [77]:
class_report = classification_report(y_test, y_pred)

In [78]:
print(class_report)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [79]:
new_df = pd.DataFrame(y_pred,y_test,columns=['Predicted Species'])

In [80]:
new_df

                Predicted Species
Species
Iris-versicolor   Iris-versicolor
Iris-setosa           Iris-setosa
Iris-virginica     Iris-virginica
Iris-versicolor   Iris-versicolor
Iris-versicolor   Iris-versicolor
Iris-setosa           Iris-setosa
Iris-versicolor   Iris-versicolor
Iris-virginica     Iris-virginica
Iris-versicolor   Iris-versicolor
Iris-versicolor   Iris-versicolor
Iris-virginica     Iris-virginica
Iris-setosa           Iris-setosa
Iris-setosa           Iris-setosa
Iris-setosa           Iris-setosa
Iris-setosa           Iris-setosa
Iris-versicolor   Iris-versicolor
Iris-virginica     Iris-virginica
Iris-versicolor   Iris-versicolor
Iris-versicolor   Iris-versicolor
Iris-virginica     Iris-virginica
Iris-setosa           Iris-setosa
Iris-virginica     Iris-virginica
Iris-setosa           Iris-setosa
Iris-virginica     Iris-virginica
Iris-virginica     Iris-virginica
Iris-virginica     Iris-virginica
Iris-virginica     Iris-virginica
Iris-virginica     Iris-virginica
Iris-setosa           Iris-setosa
Iris-setosa           Iris-setosa

In [81]:
X_train.shape

(120, 4)

In [87]:
X_test.shape

(30, 4)

In [82]:
y_train.shape

(120,)